apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: cnos-system/cnos-prometheus-agent
  name: cnos-prometheus-agent
  namespace: cnos-system
  labels:
    app: prometheus-server
    nephio.org/region: us-west1
    nephio.org/site-type: edge
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|cnos-system|cnos-prometheus-agent'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
      nephio.org/region: us-west1
      nephio.org/site-type: edge
  template:
    metadata:
      labels:
        app: prometheus-server
        nephio.org/region: us-west1
        nephio.org/site-type: edge
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        - "--web.enable-remote-write-receiver"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: cnos-prometheus-conf
      - name: prometheus-storage-volume
        emptyDir: {}
