apiVersion: v1
kind: Service
metadata: # kpt-merge: cnos-system/loki-headless
  name: loki-headless
  namespace: cnos-system
  labels:
    app: loki
    nephio.org/region: us-west1
    nephio.org/site-type: edge
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|cnos-system|loki-headless'
spec:
  clusterIP: None
  ports:
  - port: 3100
    protocol: TCP
    name: http-metrics
    targetPort: http-metrics
  selector:
    app: loki
    nephio.org/region: us-west1
    nephio.org/site-type: edge
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: cnos-system/loki-memberlist
  name: loki-memberlist
  namespace: cnos-system
  labels:
    app: loki
    nephio.org/region: us-west1
    nephio.org/site-type: edge
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|cnos-system|loki-memberlist'
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 7946
    targetPort: memberlist-port
    protocol: TCP
  selector:
    app: loki
    nephio.org/region: us-west1
    nephio.org/site-type: edge
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: cnos-system/loki
  name: loki
  namespace: cnos-system
  labels:
    app: loki
    nephio.org/region: us-west1
    nephio.org/site-type: edge
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|cnos-system|loki'
spec:
  type: ClusterIP
  ports:
  - port: 3100
    protocol: TCP
    name: http-metrics
    targetPort: http-metrics
  selector:
    app: loki
    nephio.org/region: us-west1
    nephio.org/site-type: edge
